# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160306_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='/media/logo1crop.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.User'),
        ),
    ]
