# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20160309_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
