# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:03
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20160309_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
