# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_post_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_brand', models.CharField(max_length=300)),
                ('product_buy_url', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
