# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(to='userprofile.Product'),
        ),
    ]
