# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
